[package]
name = "rust_os_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.22"
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
volatile = "0.2.7"
spin = "0.5.2"